services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ukleytech-app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
